name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # 타임아웃 설정 (긴 빌드/배포 대비)

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List workspace files
        run: ls -al

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker for Google Cloud
        run: gcloud auth configure-docker asia-northeast3-docker.pkg.dev

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            asia-northeast3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/jinshiwang-docker-repo/jinshiwang-pb-agent-ai:${{ github.sha }}
            asia-northeast3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/jinshiwang-docker-repo/jinshiwang-pb-agent-ai:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy jinshiwang-pb-agent-ai \
            --image asia-northeast3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/jinshiwang-docker-repo/jinshiwang-pb-agent-ai:${{ github.sha }} \
            --region asia-northeast3 \
            --platform managed \
            --allow-unauthenticated \
            --port 8080 \
            --timeout 1200s \
            --memory 4Gi \
            --cpu 2 \
            --max-instances 10 \
            --min-instances 1 \
            --concurrency 80 \
            --cpu-throttling \
            --execution-environment gen2 \
            --cpu-boost \
            --service-account=jinshiwang-service-account@confident-trail-468600-e6.iam.gserviceaccount.com \
            --add-cloudsql-instances=confident-trail-468600-e6:asia-northeast3:kb-pb-agent-ai-jinshiwang \
            --set-env-vars PYTHONPATH=/app,DB_HOST=/cloudsql/confident-trail-468600-e6:asia-northeast3:kb-pb-agent-ai-jinshiwang,DB_PORT=5432,DB_NAME=kb_pb_agent_ai_jinshiwang,DB_USER=${{ secrets.DB_USER }},DB_PASSWORD=${{ secrets.DB_PASSWORD }},OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }},FRED_API_KEY=${{ secrets.FRED_API_KEY }},FMP_API_KEY=${{ secrets.FMP_API_KEY }},CACHE_DIR=/app/cache,MCDONALD_CACHE_ENABLED=true,CACHE_EXPIRY_HOURS=24,ALPHAVANTAGE_API_KEY=${{ secrets.ALPHAVANTAGE_API_KEY }},HF_HOME=/app/tokenizer_cache,TRANSFORMERS_CACHE=/app/tokenizer_cache

      - name: Check deployment status
        run: |
          echo "Checking service status..."
          gcloud run services describe jinshiwang-pb-agent-ai --region asia-northeast3
          echo "Getting service URL..."
          SERVICE_URL=$(gcloud run services describe jinshiwang-pb-agent-ai --region asia-northeast3 --format="value(status.url)")
          echo "Service URL: $SERVICE_URL"
          echo "Testing health endpoint..."
          curl -f "$SERVICE_URL/health" || echo "Health check failed"
